### ISSUE TITLE
Identify requirements

### ISSUE THREAD

**Issue by bohrnsen** [saraervik/zulip#1]
Identity the requirements of the code tested in zulip/zerver/test_signup.py. Note that by requirements it means the requirements on the code being tested not the test contracts. 

#### Instructions

Identify requirements of the functions to be refactored. If the requirements are not documented yet, try to describe them based on code reviews and existing test cases.

**Comment by AdderAdder** [comment]
Each requirement has a name (ID), title, and description, and other optional attributes (in case of P+, see below). The description can be one paragraph per requirement.

**Comment by Fluffigpegasus** [comment]
We are done with this issue right? Now we have 13 functional requirements defined.

**Comment by saraervik** [comment]
No more requirements can be added now, closing this issue!
