### ISSUE TITLE
LoginOrAskForRegistrationTestCase#remote_user says returns None but returns HttpResponse

### ISSUE THREAD

**Issue by OscarMelin** [saraervik/zulip#31]
Issue arose in #17 
At https://github.com/saraervik/zulip/blob/40b82c84292b0e2281f435cd6773c1c4254cb0e8/zerver/tests/test_signup.py#L2454

should be
```python
def remote_user(self, invalid_subdomain, email='new@zulip.com') -> HttpResponse:
```

See https://www.python.org/dev/peps/pep-3107/#return-values

**Comment by saraervik** [comment]
This was fixed in PR #33
