### ISSUE TITLE
Calculate the coverage in the test cases present

### ISSUE THREAD

**Issue by bohrnsen** [saraervik/zulip#5]
The coverage archieved compared to the requirements from #1.

In the lectures as well as in the documentation Zulip provided additional tests should only be added as an separate issue, no additional tests should be added in this fork.

#### Instructions

Analyze existing test cases that relate to code being refactored. Do they contain good assertions? Do the assertions cover the requirements as you understand them? If necessary, enhance existing unit tests with properties derived from work done above, or write additional tests.

**Comment by Fluffigpegasus** [comment]
Any update on this?

**Comment by Fluffigpegasus** [comment]
Done! Can be found in the share latex file
