### ISSUE TITLE
Perform pre-testing

### ISSUE THREAD

**Issue by AdderAdder** [saraervik/zulip#6]
Run and test the program before the refactoring to evaluate the current state of the project.

#### Instructions

Carry out the unit tests, make sure they succeed (or fix the software if the fail justifiably). Keep copies of the test logs. If a test passes, make sure it was actually executed. You can use code coverage measurement (especially if this is available in the project you are using), or temporarily inject a fault (mutation) in the code, and see that at least one test fails. If you found a bug that is harder to fix than expected, document the issue (and leave an entry in the issue tracker), and attempt another refactoring, perhaps in a different project.

**Comment by Fluffigpegasus** [comment]
Any update?

**Comment by Fluffigpegasus** [comment]
Done!
