### ISSUE TITLE
Post-testing

### ISSUE THREAD

**Issue by AdderAdder** [saraervik/zulip#8]
Run the new refactored tests and validate that nothings broken by for example checking that we still have the same coverage.

#### Instructions

Run the tests on the new code. Test verdicts on the original and new code should be the same. [Unless there is a good reason, such as a bug fix that makes a previously failing test now pass.]

- [ ] This issue is dependent on issue #7. This issue should be completed.

**Comment by Fluffigpegasus** [comment]
Done! Can be found in the share latex file
